safe:        false
port: 4000
url: http://eiti-peru.github.io/eiti-peru
#url: http://localhost:4000

destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   date

rdiscount:
  extensions: []

year: 2012

locales:
  es:
    title_message: EITI Perú
    slogan_message: "Revelando la información de las industrias extractivas"
    navigation:
    - text: Inicio
      url: /index.html
    - text: Ingresos
      url: /ingresos/index.html
    - text: Empresas
      url: /empresas/index.html
    - text: Distribucion
      url: /distribucion/index.html
    - text: "Enlaces de Interés"
      url: /Enlaces/index.html
    - text: Glosario
      url: /glosario/index.html

prose:
  rooturl: _includes/editables
